version: '3'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  web:
    build: .
    command: ["pipenv", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
  celery:
    build: .
    command: ["pipenv", "run", "celery", "-A", "SelteqTask", "worker", "-l", "info"]
    volumes:
      - .:/app
    depends_on:
      - redis